# Generated by Django 5.0.3 on 2024-04-07 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='categories/logos', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
