# Generated by Django 5.0.3 on 2024-04-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='categories/logos', verbose_name='Logo'),
        ),
    ]
